website/models/VGG.py
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.applications.vgg16 import decode_predictions
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# load the model
model = VGG16()


# Create function take the image path
# 1- load image with the required size
# 2- convert image to array
# 3- reshape the image into an array (1,224,224,3)
# 4- preprocess the image convert 0-255 to 0-1
# 5- predict the image
# 6- Separate the output into an arrays and return them

def predict_image(imagePath):
    name = []
    predictions = []
    img = load_img(imagePath, target_size=(224, 224))
    img = img_to_array(img)
    img = img.reshape((1, img.shape[0], img.shape[1], img.shape[2]))
    img = preprocess_input(img)
    yhat = model.predict(img)
    label = decode_predictions(yhat)
    for lab in label[0]:
        name.append(lab[1])
        predictions.append(lab[2] * 100)

    label = label[0][0]

    classification = '%s (%.2f%%)' % (label[1], label[2] * 100)

    return classification, name, predictions

website/__init__.py
from flask import Flask, session
from flask_sqlalchemy import SQLAlchemy
from flask_session import Session
from os import path
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
DB_NAME = "database.db"

UPLOAD_FOLDER = 'website/static/uploads/'

def create_app():
    app = Flask(__name__)
    app.secret_key = "secret key"
    app.config['SESSION_TYPE'] = 'filesystem'
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024
    Session(app)
    Bootstrap(app)

    # Define the database with flask
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .collectData import collectData
    from .views_projects import views_projects
    from .views_training import views_training

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(collectData, url_prefix='/')
    app.register_blueprint(views_projects, url_prefix='/')
    app.register_blueprint(views_training, url_prefix='/')

    from .database_model import Project, Classes
    create_database(app)

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

app = create_app()

website/views.py
from flask import request, redirect, render_template
from flask import session, send_from_directory, url_for, Response
from wtforms import SelectField, FileField, SubmitField
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileAllowed
import cv2

# import flash to show the text message https://flask.palletsprojects.com/en/1.1.x/patterns/flashing/
from flask import flash, Blueprint, url_for
import os
from werkzeug.utils import secure_filename
from .database_model import Project, Classes, db
from wtforms_sqlalchemy.fields import QuerySelectField
# from .models import VGG as model

views = Blueprint('views', __name__)

UPLOAD_FOLDER = 'website/static/uploads/'
# This helper function use to check the extension of the file to make sure we load images
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif', 'jfif'])


class LoadImage(FlaskForm):
    image = FileField('image', validators=[FileRequired()])
    submit = SubmitField('Predict')


def generate_frames(filename):
    ## read the camera frame
    print(filename)
    frame = cv2.imread(filename)
    try:
        ret, buffer = cv2.imencode('.jpg', frame)
        frame = buffer.tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
    except Exception as e:
        flash("No image was captured", category='error')
        pass
    else:
        pass

@views.route('/display/<filename>')
def imshow(filename):
    print(filename)
    return Response(generate_frames(filename), mimetype='multipart/x-mixed-replace; boundary=frame')

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@views.route('/')
def home_page():
    session['project'] = 'None'
    return render_template("home.html")

@views.route("/prediction", methods=["GET", "POST"])
def prediction_page():
    form = LoadImage()
    file_url = None
    if form.validate_on_submit():
        file = form.image.data
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(UPLOAD_FOLDER, filename))

            # Get the full path of the image and pass it into the model
            # to predict the image content
            img_path = os.path.join(UPLOAD_FOLDER, filename)
            print(img_path)
            flash('Image successfully uploaded and displayed below', category='success')
            # classification, labels, values = model.predict_image(img_path)
            classification = 'none'
            file_url = img_path
            #return render_template('prediction.html', filename=img_path, prediction=classification, max=100, form=form)
        else:
            flash('Allowed image types are - png, jpg, jpeg, gif', category='error')
            #return redirect(request.url)
    return render_template('prediction.html', form=form, file_url=file_url)

website/templates/create_project.html
{% extends "layout.html" %}
{% block title %}List{% endblock %}
{% block content %}
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<style>
.input-wrapper div {
    margin-bottom: 10px;
}
.remove-input {
    margin-top: 10px;
    margin-left: 15px;
    vertical-align: text-bottom;
}
.add-input {
    margin-top: 10px;
    margin-left: 10px;
    vertical-align: text-bottom;
}
</style>

  <div style="width:85%;padding:50px;">
    <h2>Create New Project</h2>
    {% if message %}
          <div class="alert alert-success">{{message}}</div>
    {% endif %}
    <form method="POST">
        <label for="name">Project name</label>
        <input
                type="name"
                class="form-control"
                id="name"
                name="name"
                placeholder="Enter project name"
        />
        <label for="description">Project Description</label>
        <input
                type="description"
                class="form-control"
                id="description"
                name="description"
                placeholder="Enter project description"
        />
        <div class="input-wrapper">
            <div>Classes : <br/>
            <input type="text" name="class[]" value=""/>
            <a href="javascript:void(0);" class="add-input" title="Add input"><img src="/static/img/add.png"/></a>
            </div>
        </div>
        <input type="submit" name="cmdsubmit">
    </form>

  </div>
<script>
$(document).ready(function(){
    var max_input_fields = 10;
    var add_input = $('.add-input');
    var input_wrapper = $('.input-wrapper');
    var new_input = '<div><input type="text" name="class[]" value=""/><a href="javascript:void(0);" class="remove-input" title="Remove input"><img src="/static/img/remove.png"/></a></div>';
    var add_input_count = 1;
    $(add_input).click(function(){
        if(add_input_count < max_input_fields){
            add_input_count++;
            $(input_wrapper).append(new_input);
        }
    });
    $(input_wrapper).on('click', '.remove-input', function(e){
        e.preventDefault();
        $(this).parent('div').remove();
        add_input_count--;
    });
});
</script>
{% endblock %}

website/templates/datacollection.html
{% extends "layout.html" %}
{% block title %}Data Collection{% endblock %}

{% block content %}

<div class="container-md">
    <div class="row" style="border:1px solid red;">
        <div class="col" >
            <h1 style="text-align:center;">Data Collection</h1>
            <h3 style="text-align:center;">{{ session['project'] }}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4" style="border:1px solid red;">
            <div class="form-group col-xs-6">
                <h4>Select class to save data</h4>
                <form action="/datacollection" method="POST" enctype="multipart/form-data">
                    {{form.csrf_token}}
                    {{ form.opts}}
                    <ul>
                        {% for error in form.opts.errors %}
                        <li style="color:red;">{{ error }}</li>
                        {% endfor %}
                    </ul>
                    <input type="submit">
                </form>
            </div>

        <table>
            <thread>
                <tr>
                    <th>ID</th>
                    <th>Class name</th>
                    <th>Number of Items</th>
                    <th>Project ID</th>
                </tr>
            </thread>
            <tbody>
                {% for cls in classes %}
                <tr>
                    <td> {{ cls.id }} </td>
                    <td> {{ cls.className }} </td>
                    <td> {{ cls.items_number }} </td>
                    <td> {{ cls.project_id }} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        </div>
            <div class="col-md-8 text-center" style="border:1px solid red;">
                    <h2 class="mt-5" >Collect Data sets</h2>
                    <form method="post" action="{{ url_for('collectData.tasks') }}">
                    <input type="submit" value="Stop/Start" name="stop" />
                    <input type="submit" value="Capture" name="click"/>
                    </form>
                    <img src="{{ url_for('collectData.video') }}" height="30%">
            </div>
        </div>
    </div>
{% endblock %}

website/templates/home.html
{% extends "layout.html" %}
{% block title %}Inspection Box{% endblock %}
{% block content %}
    <h1>Inspection Box</h1>
    <p>Inspection box is an open source software integrated with nvidia jetson nano.
        The pupose of the inspection box is to use as tools in industrial inspection
        where it provide an easy solution for integrating a visual inspection.
    </p>
{% endblock %}

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Inspection box - {% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css"/>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <header>
      <nav class="navbar" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="button is-link" href="/">Home</a>
            <a class="button is-link" href="/createproject">Create project</a>
            <a class="button is-link" href="/select_project">Select project</a>
            {% if not session['project'] == 'None' %}
            <a class="button is-link" href="/project_info">Project Info</a>
            <a class="button is-link" href="/prediction">Prediction</a>
            <a class="button is-link" href="/datacollection">Data collection</a>
            <a class="button is-link" href="/train_page">Training</a>
            {% endif %}
        </div>
      </nav>
    </header>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}


     <main>
      <section class="section">
        <div class="content">
          {% block content %}{% endblock %}
        </div>
      </section>
    </main>

     <footer class="footer">
      <div class="content">
        <small>&copy; 2022, Abdulla Mohamed</small>
      </div>
    </footer>

  </body>
</html>

website/templates/list.html
{% extends "layout.html" %}
{% block title %}List{% endblock %}
{% block content %}
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<style>
.input-wrapper div {
    margin-bottom: 10px;
}
.remove-input {
    margin-top: 10px;
    margin-left: 15px;
    vertical-align: text-bottom;
}
.add-input {
    margin-top: 10px;
    margin-left: 10px;
    vertical-align: text-bottom;
}
</style>

  <div style="width:85%;padding:50px;">
    <h2>Create New Project</h2>
    {% if message %}
          <div class="alert alert-success">{{message}}</div>
    {% endif %}
    <form method="POST">
        <label for="name">Project name</label>
        <input
                type="name"
                class="form-control"
                id="name"
                name="name"
                placeholder="Enter project name"
        />
        <div class="input-wrapper">
            <div>Classes : <br/>
            <input type="text" name="class[]" value=""/>
            <a href="javascript:void(0);" class="add-input" title="Add input"><img src="/static/img/add.png"/></a>
            </div>
        </div>
        <input type="submit" name="cmdsubmit">
    </form>

  </div>
<script>
$(document).ready(function(){
    var max_input_fields = 10;
    var add_input = $('.add-input');
    var input_wrapper = $('.input-wrapper');
    var new_input = '<div><input type="text" name="class[]" value=""/><a href="javascript:void(0);" class="remove-input" title="Remove input"><img src="/static/img/remove.png"/></a></div>';
    var add_input_count = 1;
    $(add_input).click(function(){
        if(add_input_count < max_input_fields){
            add_input_count++;
            $(input_wrapper).append(new_input);
        }
    });
    $(input_wrapper).on('click', '.remove-input', function(e){
        e.preventDefault();
        $(this).parent('div').remove();
        add_input_count--;
    });
});
</script>
{% endblock %}

website/templates/prediction.html
{% extends "layout.html" %}
{% block title %}Prediction{% endblock %}

<head>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

{% block content %}
<h2>Select image for the prediction</h2>
<div class="container">
    <div class="row">
        <br>
            <form method="post" action="" enctype="multipart/form-data">
                <div class="row justify-content-center">
                    <div class="col-auto">
                        {{ form.csrf_token }}
                        {{ form.image(class="form-control") }}
                    </div>
                    <div class="col-auto">
                        <input type="submit" value="Submit" class="btn btn-info">
                    </div>
                </div>
            </form>
            {% if file_url %}
                <div class="mt-5">
                    <h3>Image</h3>
                    <img src="{{ url_for('views.imshow', filename=filename) }}" style="width: 400px;">
                </div>
            {% endif %}
            {%if prediction%}
                <p align="center">The image load is {{prediction}} </p>
            {% endif%}
    </div>
</div>

{% endblock %}

website/templates/project_info.html
{% extends "layout.html" %}
{% block title %}Project Information{% endblock %}
{% block content %}

<h1>Project name: {{session['project']}}</h1>
<table>
    <thread>
        <tr>
            <th>ID</th>
            <th>Class name</th>
            <th>Number of Items</th>
            <th>Project ID</th>
        </tr>
    </thread>
    <tbody>
        {% for cls in classes %}
        <tr>
            <td> {{ cls.id }} </td>
            <td> {{ cls.className }} </td>
            <td> {{ cls.items_number }} </td>
            <td> {{ cls.project_id }} </td>

            <td>
                <form method="POST" action="{{ url_for('views_projects.delect_class', class_id=cls.id) }}">
                    <input type="submit" value="Delete">
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div>
    <h3>Add new class</h3>
    <form method="POST" action="/project_info">
        {{ form.csrf_token }}
        {{ form.class_name.label }} {{ form.class_name(size=20) }}
        <input type="submit" value="Add Class">
    </form>
</div>
<div>
    <h3>Delete class</h3>
    <form method="POST" action="{{ url_for('views_projects.delect_class', class_id=3) }}">
        <input type="submit" value="Add Class">
    </form>
</div>
{% endblock %}

website/templates/selectProject.html
{% extends "layout.html" %}
{% block title %}Select Project{% endblock %}
{% block content %}
    <form action="/select_project" method="POST">
        {{form.csrf_token}}
        {{ form.opts}}
        <ul>
            {% for error in form.opts.errors %}
            <li style="color:red;">{{ error }}</li>
            {% endfor %}
        </ul>
        <input type="submit">
    </form>
{% endblock %}

website/templates/train.html
{% extends "layout.html" %}
{% block title %}Training{% endblock %}
{% block content %}

{% import "bootstrap/wtf.html" as wtf %}
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <h2>Training hyperparamters</h2>
            <form action="" method="post" class="form" role="form">
                <div class="row">
                    <div class="form-group">
                        {{ wtf.form_field(form.select_model) }}
                        {{ wtf.form_field(form.batch_size) }}
                        {{ wtf.form_field(form.learning_rate) }}
                        {{ wtf.form_field(form.optimizer) }}
                        {{ wtf.form_field(form.loss_function) }}
                    </div>
                </div>
                {{ form.submit_setup(class="btn btn-outline-info") }}
                {{ form.submit_start(class="btn btn-outline-info") }}
                {{ form.submit_stop(class="btn btn-outline-danger") }}
                <br>
                    {{ form.submit_save_model(class="btn btn-outline-info") }}
                </br>
            </form>
        </div>
        <div class="col-sm">
          One of three columns
        </div>
      </div>
    </div>
{% endblock %}